[package]
name = "solana-privacy-pools"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = "0.9"
pinocchio-token = "0.4"
pinocchio-log = "0.5"
groth16-solana = { path = "vendor/groth16-solana", features = [
    "debug-groth16",
] }
lean-imt = { path = "vendor/lean-imt", default-features = false }
poseidon-ark-vendored = { path = "vendor/poseidon-ark" }
bs58 = { version = "0.5", default-features = false, features = ["alloc"] }
ark-ff = { version = "0.5", default-features = false }
ark-bn254 = { version = "0.5", default-features = false }

[lib]
crate-type = ["cdylib", "lib"]

[features]
test-utils = []
test-precomputed-hashes = []
custom-heap = []
custom-panic = []

[dev-dependencies]
solana-program-test = "2.1"
solana-sdk = "2.1"
spl-token = "6.0"
tokio = { version = "1.40", features = ["full"] }
anyhow = "1.0"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
